@startuml

abstract class Character{
    + name: String
    + maxHp: int
    + hp: int
    + xp: int
    + Character(name, maxHp, xp)
    + {abstract} attack(): int
    + {abstract} defend(): int
}

class Main{
    + {static} main(String[]): void
}

class Player{
    + numAtkUpgrades: int
    + numDefUpgrades: int
    + atkUpgrades: String[]
    + defUpgrades: String[]
    gold: int
    restsLeft: int
    pots: int
    + Player(String)
    + chooseTrait(): void
    + attack(): int
    + defend(): int
}

class Enemy{
    playerXp: int
    + Enemy(String, int)
    + attack(): int
    + defend(): int
}

class Story{
    + {static} printIntro(): void
    + {static} printFirstActIntro(): void
    + {static} printFirstActOutro(): void
    + {static} printSecondActIntro(): void
    + {static} printSecondActOutro(): void
    + {static} printThirdActIntro(): void
    + {static} printThirdActOutro(): void
    + {static} printFourthActIntro(): void
    + {static} printEnd(Player): void
}

class GameLogic{
    + {static} isRunning: boolean
    + {static} encounters: String[]
    + {static} enemies: String[]
    + {static} place: int
    + {static} act: int
    + {static} places: String[]
    player: Player
    scanner: Scanner
    + {static} readInt(String, int): int
    + {static} clearConsole(): void
    + {static} printSeparator(int): void
    + {static} printHeading(String): void
    + {static} anythingToContinue(): void
    + {static} startGame(): void
    + {static} checkAct(): void
    + {static} randomEncounter(): void
    + {static} continueJourney(): void
    + {static} shop(): void
    + {static} takeRest(): void
    + {static} randomBattle(): void
    + {static} battle(Enemy): void
    + {static} printMenu(): void
    + {static} finalBattle(): void
    + {static} playerDied(): void
    + {static} gameLoop(): void
}

Character <|-- Player
Character <|-- Enemy
GameLogic --> Player : manages
GameLogic --> Enemy : creates
GameLogic --> Story : calls methods
Story --> Player : references
Main --> GameLogic : calls methods

@enduml